Add retries feature
luxteam/jobs_test_rprviewer pull request #38
Opened 2020-09-07 14:00 UTC by Kataderon

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1490

## RELATED PR'S

## REPORTS

2020-09-10 10:01 UTC, Piromancer requested changes
Нет отчетов

2020-09-14 11:21 UTC, Piromancer requested changes
https://rpr.cis.luxoft.com/job/viewer_retries_test/6/Test_20Report/
Не прошли тесты

2020-09-17 20:44 UTC, epozine submitted a review, later dismissed
По коду все ок.
Также хотелось бы увидеть в данном ПРе:
1. Логирование ретрая, чтобы в логе было явно отражено, что был ретрай
2. Прогон, в котором ты запустишь какую-то группу, зайдешь на машину и попробуешь поубивать вьер, посмотри как он будет восстанвливаться. Отчет с логами о ретраях приложи. Мне кажется так будет полноценное тестирование

2020-09-17 20:44 UTC, epozine commented on jobs/Scripts/simpleRender.py
> +        while i < args.retries and test_case_status ==TEST_CRASH_STATUS:
```suggestion
        while i < args.retries and test_case_status == TEST_CRASH_STATUS:
```

2020-09-22 17:48 UTC, epozine commented
Ожидаются обновления в данном ПРе?

2020-09-24 13:46 UTC, Piromancer commented
https://rpr.cis.luxoft.com/job/viewer_retries/11/Test_20Report/

2020-09-24 13:46 UTC, Piromancer requested changes
^

2020-09-24 14:29 UTC, Piromancer approved these changes

2020-09-25 08:14 UTC, epozine approved these changes

2020-09-25 08:14 UTC, epozine commented on jobs/Tests/Denoiser/test.cases.json
> +            "draw_engine": "-"
```suggestion
            "draw_engine": "vw_d3d12"
```

2020-09-25 08:18 UTC, epozine approved these changes

2020-09-25 08:22 UTC, merged