Exit testing if first 3 cases are error
luxteam/jobs_test_rprviewer pull request #52
Opened 2020-10-09 16:02 UTC by Kataderon

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-1690

## REPORTS

2020-10-12 15:46 UTC, Piromancer requested changes

2020-10-12 15:46 UTC, Piromancer commented on jobs/Scripts/simpleRender.py
> +        if test_case_status == TEST_CRASH_STATUS:
В тикете ведь сказано первые три кейса подряд. Тут такой логики не реализовано

2020-10-12 15:56 UTC, epozine commented
Как ты проверял свои изменения? Я вижу только успешный отчет. 
И Денис все правильно подметил, речь в данном случае только про 3 первые подряд, желательно параметром. 
Если хоть один тест успешный, то далее условие про 3 кейса не нужно.

2020-10-13 11:34 UTC, Piromancer requested changes
Жду фикса случая со скипнутыми кейсами

2020-10-19 09:47 UTC, Piromancer approved these changes

2020-10-19 09:51 UTC, Piromancer requested changes
https://rpr.cis.luxoft.com/job/RadeonProViewerManual/894/Test_20Report/AMD_RadeonVII-Windows-Camera/Results/RprViewer/Camera/report.html
Если так завершать кейсы, то пишет что вышло по таймауту. Можно сделать чтобы было написано:
"Test execution was interrupted due to first 3 cases resulting in error"

2020-10-19 14:43 UTC, epozine commented
Привет
Завершать работу если третий кейс error и если три первые кейса error это две разные задачи. Нам нужна вторая

2020-10-19 15:22 UTC, epozine submitted a review, later dismissed

2020-10-19 15:24 UTC, epozine commented
Хотелось бы реализовать пожелание Дениса о "Test execution was interrupted due to first 3 cases resulting in error".

2020-10-20 09:39 UTC, Kataderon commented
> https://rpr.cis.luxoft.com/job/RadeonProViewerManual/894/Test_20Report/AMD_RadeonVII-Windows-Camera/Results/RprViewer/Camera/report.html
> Если так завершать кейсы, то пишет что вышло по таймауту. Лучше сделать чтобы было написано:
> "Test execution was interrupted due to first 3 cases resulting in error".
> И еще нужно пофиксить мердж конфликт

Всё сделано по тз из тикета. Пожалуйста, указывайте более точное описание изменений в тикете

2020-10-20 09:42 UTC, epozine commented
Где в тикете написано, что в случае 3 error кейсов писать вышел таймаут?

2020-10-20 09:43 UTC, epozine commented
Логически подумай, тебе же самому будет проще потом определять причину error, если ты ее явно напишешь

2020-10-20 09:44 UTC, Kataderon commented
> Где в тикете написано, что в случае 3 error кейсов писать вышел таймаут?

В тикете вообще не описано это поведение.

2020-10-22 14:02 UTC, Piromancer commented
А Animation тесты специально завалили? Если нет, то меня смущают эти ошибки. Прежде чем мерджить ПР возможно стоит попробовать пофиксить эти проблемы, а так вопросов больше не имею

2020-10-22 15:57 UTC, Piromancer approved these changes

2020-10-27 10:01 UTC, epozine commented
Message: Test execution was interrupted due to first 3 cases resulting in error. Test group timeout exceeded
Откуда второе предложение про таймаут берется и зачем?

2020-11-11 19:32 UTC, epozine commented on jobs/Scripts/simpleRender.py
> +                test_case_report["message"] = ['Test execution was interrupted due to first ' + str(args.error_until_group_failed) + ' cases resulting in error']
```suggestion
                test_case_report["message"] = ['Test execution was interrupted due to the first ' + str(args.error_until_group_failed) + ' cases resulting in an error']
```

2020-11-11 19:33 UTC, epozine approved these changes
Ждем окончания релиза для мержа

2020-12-07 17:10 UTC, merged