Refactoring. Changed names and files. (Changed jobs_launcher)
luxteam/jobs_test_rprviewer pull request #59
Opened 2020-12-30 01:21 UTC by Flame0n

### **Jira Ticket** 

- https://adc.luxoft.com/jira/browse/STVCIS-1760

### **Purpose**

- Change the name of files and fields

### **Effect of change**

- After changes, the tests and their contents will be more similar to the rest of the jobs.

### **Jenkins Builds**

- https://rpr.cis.luxoft.com/job/RadeonProViewerManual/956/

2020-12-30 07:10 UTC, Speedwag00n requested changes
Нужно решить конфликт. Также нужно будет посмотреть на результаты билда
Здесь тоже нужно не забыть поменять сабмодуль, как и в репозитории Макса

2020-12-30 07:10 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +<<<<<<< HEAD
Конфликт не решен

2021-01-11 00:01 UTC, Flame0n commented on jobs/Scripts/simpleRender.py
> +<<<<<<< HEAD
Решил конфликты.

2021-01-11 04:35 UTC, Flame0n commented
Новый результат после решения конфликтов
https://rpr.cis.luxoft.com/job/RadeonProViewerManual/962/

2021-01-11 07:21 UTC, Speedwag00n approved these changes
Теперь все хорошо.
Нужно только конфликт с сабмодулем решить.
Еще нужно будет поменять в этой строке test.cases.json на test_cases.json. Но это уже в совершенно другом репозитории:
https://github.com/luxteam/rpr_pipelines/blame/2398b3fa7f8d509541bb316a743c1d9d7ec39b32/vars/rpr_viewer_pipeline.groovy#L732

2021-01-11 15:33 UTC, Speedwag00n submitted a review, later dismissed

2021-01-12 10:53 UTC, closed without merging